# EXPERIMENT 2)

**NUMERICAL PYTHON (NUMPY)**

Daphne P. Robleado
*2ECE-A*

September 1, 2024

* **NORMALIZATION PROBLEM:**

In [19]:
import numpy as np

#Making and printing a random 5x5 array matrix
X = np.random.rand(5, 5)

print("Original ndarray X:")
print(X)

#Normalization function
mean = X.mean()
std_dev = X.std()

X_normalized = (X - mean) / std_dev

print("\nNormalized ndarray:")
print(X_normalized)

#saving the value of normalization function
np.save('X_normalized.npy', X_normalized)

Original ndarray X:
[[0.64819084 0.55085209 0.02933441 0.54838157 0.46593195]
 [0.74213252 0.38973642 0.74366669 0.65017392 0.92304056]
 [0.62868188 0.08660264 0.01318719 0.55447082 0.72971829]
 [0.8637471  0.37584521 0.2276567  0.54135645 0.58627091]
 [0.25911407 0.80624174 0.71379724 0.128185   0.05498918]]

Normalized ndarray:
[[ 0.58397664  0.22361116 -1.70714069  0.21446484 -0.09077841]
 [ 0.93176556 -0.37286792  0.93744531  0.59131835  1.6015195 ]
 [ 0.51175096 -1.49512343 -1.76692057  0.23700835  0.88580584]
 [ 1.38200451 -0.42429566 -0.97291606  0.18845658  0.35473797]
 [-0.85645525  1.16910936  0.82686326 -1.34117809 -1.61216213]]


* **DIVISIBLE BY 3 PROBLEM**

In [18]:
import numpy as np

#Creating a matrix of perfect square values from 1-100
A = np.array([i**2 for i in range(1, 101)])

#Reshaping it to 10x10
A = A.reshape(10, 10)

#Printing the values
print("Squared values from 1-100:")
print(A)

#Divisible by 3 function
div_by_3 = A[A % 3 == 0]

print("\nElements divisible by 3:")
print(div_by_3)

#Saving the value of the function as np
np.save('div_by_3.npy', div_by_3)

Squared values from 1-100:
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements divisible by 3:
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
